# Generated by Django 3.0.1 on 2019-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0003_bidrecord_sellitem_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
