# Generated by Django 3.0.1 on 2019-12-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0005_auto_20191218_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='current_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_bidder', to='ciftlikbank.Person'),
        ),
    ]
