# Generated by Django 3.0.1 on 2019-12-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0007_auto_20191218_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='auction_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
