# Generated by Django 3.0.1 on 2019-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0008_sellitem_auction_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrecord',
            name='bidder_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
