# Generated by Django 3.0.1 on 2019-12-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0009_bidrecord_bidder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='auction_ended_at',
            field=models.DateTimeField(null=True),
        ),
    ]
