# Generated by Django 3.0 on 2019-12-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0009_bidrecord_bidder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
    ]
