# Generated by Django 3.0.1 on 2019-12-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0010_sellitem_auction_ended_at'),
        ('ciftlikbank', '0010_sellitem_current_value'),
    ]

    operations = [
    ]
