# Generated by Django 3.0 on 2019-12-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ciftlikbank', '0011_auto_20191218_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidrecord',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
