# Generated by Django 3.0 on 2019-12-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0012_auto_20191218_2005'),
        ('ciftlikbank', '0012_auto_20191218_1957'),
    ]

    operations = [
    ]
