# Generated by Django 3.0 on 2019-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0013_merge_20191218_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verification_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
