# Generated by Django 3.0 on 2019-12-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0015_auto_20191219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidrecord',
            name='bidder_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='namesurname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='verification_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='auction_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='itemtype',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
