# Generated by Django 2.2 on 2019-12-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0017_sellitem_old_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Ciftlikbank/media'),
        ),
    ]
