# Generated by Django 2.2 on 2020-01-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0020_auto_20191219_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='item_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('item', 'ITEM'), ('user', 'USER')], max_length=4, null=True),
        ),
    ]
