# Generated by Django 2.2 on 2020-01-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciftlikbank', '0021_auto_20200106_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='item_type',
            new_name='itemtype',
        ),
    ]
